#!/bin/sh

# PROVIDE: peertube
# REQUIRE: LOGIN postgresql nginx redis
# KEYWORD: shutdown

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

. /etc/rc.subr

desc="Peertube daemon"
name=peertube
rcvar=peertube_enable

load_rc_config $name

: ${peertube_enable:=NO}

sig_stop=HUP
peertube_chdir="/var/www/peertube/peertube-latest"
peertube_env="HOME=/var/www/peertube \
NODE_ENV=production \
NODE_CONFIG_DIR=/var/www/peertube/config \
USER=peertube"
peertube_user=peertube
procname="node:"
pidfile="/var/run/peertube.pid"

command="/usr/sbin/daemon"
command_args="-p ${pidfile} -o /var/log/peertube/${name}.log -t ${name} -u ${peertube_user} /usr/local/bin/npm start"

run_rc_command "$1"
