version: '3'

services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=peertube
      - POSTGRESQL_PASSWORD=peertube
      - POSTGRESQL_DATABASE=peertube_dev
    volumes:
      - postgresql_data:/bitnami/postgresql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8001:80"

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      #- REDIS_PASSWORD=my_redis_password
    volumes:
      - redis_data:/bitnami/redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8002:8081"

volumes:
  postgresql_data:
    driver: local

  redis_data:
    driver: local
