/* oxlint-disable @typescript-eslint/no-unused-expressions,@typescript-eslint/require-await */

import {
  cleanupTests,
  createSingleServer,
  PeerTubeServer,
  PluginsCommand,
  setAccessTokensToServers,
  setDefaultVideoChannel,
  waitJobs
} from '@peertube/peertube-server-commands'
import { getCaptionContent, uploadForTranscription } from '@tests/shared/transcription.js'
import { expect } from 'chai'

describe('Test plugin transcription', function () {
  let server: PeerTubeServer

  before(async function () {
    this.timeout(60000)

    server = await createSingleServer(1)

    await setAccessTokensToServers([ server ])
    await setDefaultVideoChannel([ server ])

    await server.config.enableTranscription()

    await server.plugins.install({ path: PluginsCommand.getPluginTestPath('-transcription') })
  })

  it('Should generate subtitles with the transcriber provided by a plugin', async function () {
    this.timeout(60000)

    const uuid = await uploadForTranscription(server)
    await waitJobs([ server ])

    const { total, data } = await server.captions.list({ videoId: uuid })

    expect(total).to.equal(1)
    expect(data).to.have.lengthOf(1)
    expect(data[0].automaticallyGenerated).to.be.true
    expect(data[0].language.id).to.equal('en')

    const content = await getCaptionContent(server, uuid, 'en')
    expect(content).to.contain('Generated by the test plugin transcriber')
  })

  after(async function () {
    await cleanupTests([ server ])
  })
})
