// Order of the tests we want to execute
import './create-import-video-file-job'
import './create-generate-storyboard-job'
import './create-move-video-storage-job'
import './house-keeping.js'
import './peertube'
import './plugins'
import './prune-storage'
import './regenerate-thumbnails'
import './reset-password'
import './update-host'
import './update-object-storage-url.js'
