---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - typescript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- config/
- node_modules/
- scripts/
- server/tests/
- .tmp/
