packages:
  - packages/*
  - apps/*
  - server
  - client
  - client/packages/*
  - client/src/standalone/player

blockExoticSubdeps: false

ignoredBuiltDependencies:
  - sharp

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - bcrypt
  - bufferutil
  - core-js
  - edgedriver
  - es5-ext
  - esbuild
  - geckodriver
  - lmdb
  - msgpackr-extract
  - node-datachannel
  - protobufjs
  - utf-8-validate
  - utp-native

overrides:
  '@types/express': 4.17.9
  '@types/express-serve-static-core': 4.19.5
  p2p-media-loader-core: github:Chocobozzz/p2p-media-loader#v4-external-test&path:packages/p2p-media-loader-core
  p2p-media-loader-hlsjs: github:Chocobozzz/p2p-media-loader#v4-external-test&path:packages/p2p-media-loader-hlsjs

patchedDependencies:
  sharp: pnpm-patches/sharp.patch
  tinykeys: pnpm-patches/tinykeys.patch
  video.js: pnpm-patches/video.js.patch
