// Order of the tests we want to execute
import './accounts'
import './follows'
import './jobs'
import './services'
import './users'
import './video-abuses'
import './video-blacklist'
import './video-captions'
import './video-channels'
import './video-comments'
import './videos'
import './video-imports'
import './search'
import './user-subscriptions'
