// Order of the tests we want to execute
import './follows'
import './jobs'
import './services'
import './users'
import './video-abuses'
import './video-blacklist'
import './video-channels'
import './video-comments'
import './videos'
