/* oxlint-disable @typescript-eslint/no-unused-expressions */

import { HttpStatusCode, UserRole } from '@peertube/peertube-models'
import {
  cleanupTests,
  createSecondaryServer,
  createSingleServer,
  PeerTubeServer,
  PluginsCommand,
  setAccessTokensToServers
} from '@peertube/peertube-server-commands'
import { fetchExternalToken } from '@tests/shared/plugins.js'
import { expect } from 'chai'

describe('Test external auth plugins with a secondary server process', function () {
  let primary: PeerTubeServer
  let secondary: PeerTubeServer

  let kefkaId: number

  // The plugin authentication routes are only served by the primary, the login request can reach any process
  function fetchToken (authName: 'external-auth-1' | 'external-auth-2', query?: Record<string, string>) {
    return fetchExternalToken({ server: primary, npmName: 'test-external-auth-one', authName, query })
  }

  before(async function () {
    this.timeout(120000)

    primary = await createSingleServer(1, {
      rates_limit: {
        login: {
          max: 30
        }
      }
    })

    await setAccessTokensToServers([ primary ])

    await primary.plugins.install({ path: PluginsCommand.getPluginTestPath('-external-auth-one') })

    secondary = await createSecondaryServer(primary)
  })

  it('Should exchange on the secondary a token generated by the primary', async function () {
    const externalAuthToken = await fetchToken('external-auth-1', { username: 'cyan' })

    const { body } = await secondary.login.loginUsingExternalToken({ username: 'cyan', externalAuthToken })

    const { username } = await primary.users.getMyInfo({ token: body.access_token })
    expect(username).to.equal('cyan')
  })

  it('Should not replay on a process a token consumed by another one', async function () {
    const externalAuthToken = await fetchToken('external-auth-1', { username: 'cyan' })

    await secondary.login.loginUsingExternalToken({ username: 'cyan', externalAuthToken })

    await primary.login.loginUsingExternalToken({ username: 'cyan', externalAuthToken, expectedStatus: HttpStatusCode.BAD_REQUEST_400 })
  })

  it('Should run the onLogout function of the plugin on the secondary', async function () {
    const externalAuthToken = await fetchToken('external-auth-1', { username: 'cyan' })
    const { body } = await secondary.login.loginUsingExternalToken({ username: 'cyan', externalAuthToken })

    await secondary.login.logout({ token: body.access_token })

    await secondary.servers.waitUntilLog('On logout cyan')
  })

  it('Should create on the secondary the user of a plugin returning a user updater', async function () {
    const externalAuthToken = await fetchToken('external-auth-2')
    const { body } = await secondary.login.loginUsingExternalToken({ username: 'kefka', externalAuthToken })

    const me = await secondary.users.getMyInfo({ token: body.access_token })
    expect(me.username).to.equal('kefka')
    expect(me.account.displayName).to.equal('Kefka Palazzo')
    expect(me.role.id).to.equal(UserRole.ADMINISTRATOR)
    expect(me.videoQuota).to.equal(42000)
    expect(me.videoQuotaDaily).to.equal(42100)
    expect(me.language).to.equal('fr')

    kefkaId = me.id
  })

  it('Should apply on the secondary the user updater results computed by the primary', async function () {
    await primary.users.update({ userId: kefkaId, videoQuota: 43000, videoQuotaDaily: 43100 })

    const externalAuthToken = await fetchToken('external-auth-2')
    const { body } = await secondary.login.loginUsingExternalToken({ username: 'kefka', externalAuthToken })

    // The updater of the plugin uses its new value for every field but videoQuotaDaily
    const me = await secondary.users.getMyInfo({ token: body.access_token })
    expect(me.videoQuota).to.equal(42000)
    expect(me.videoQuotaDaily).to.equal(43100)
  })

  it('Should refuse user updater results computed against an account that changed since', async function () {
    const externalAuthToken = await fetchToken('external-auth-2')

    // After the primary ran the updater of the plugin
    await primary.users.update({ userId: kefkaId, videoQuotaDaily: 44100 })

    await secondary.login.loginUsingExternalToken({
      username: 'kefka',
      externalAuthToken,
      expectedStatus: HttpStatusCode.BAD_REQUEST_400
    })

    // A new authentication runs the updater against the current account
    const retryToken = await fetchToken('external-auth-2')
    const { body } = await secondary.login.loginUsingExternalToken({ username: 'kefka', externalAuthToken: retryToken })

    const me = await secondary.users.getMyInfo({ token: body.access_token })
    expect(me.videoQuotaDaily).to.equal(44100)
  })

  after(async function () {
    await cleanupTests([ secondary, primary ])
  })
})
