export enum UserRight {
  ALL,

  MANAGE_USERS,
  MANAGE_SERVER_FOLLOW,
  MANAGE_VIDEO_ABUSES,
  MANAGE_JOBS,
  MANAGE_CONFIGURATION,

  MANAGE_VIDEO_BLACKLIST,

  REMOVE_ANY_VIDEO,
  REMOVE_ANY_VIDEO_CHANNEL,
  REMOVE_ANY_VIDEO_COMMENT,
  UPDATE_ANY_VIDEO
}
