webserver:
  hostname: "PEERTUBE_HOSTNAME"

admin:
  email: "PEERTUBE_ADMIN_EMAIL"

signup:
  enabled:
    __name: "PEERTUBE_SIGNUP_ENABLED"
    __format: "json"

transcoding:
  enabled:
    __name: "PEERTUBE_TRANSCODING_ENABLED"
    __format: "json"
