version: "3.3"

services:
  app:
    image: decentralize/peertube
    environment:
      PEERTUBE_HOSTNAME: peertube.example.com
      PEERTUBE_ADMIN_EMAIL: admin@example.com
      PEERTUBE_SIGNUP_ENABLED: "false"
      PEERTUBE_TRANSCODING_ENABLED: "true"
    labels: &labels
      traefik.frontend.rule: "Host:peertube.example.com"
      traefik.docker.network: traefik
      traefik.port: "9000"
    volumes:
      - app_data:/usr/src/app/data
    networks:
      - traefik
      - backend
    depends_on:
      - db
    deploy:
      labels: *labels
      placement:
        constraints:
        - node.labels.peertube == 1

  db:
    image: postgres:10
    environment:
      POSTGRES_DB: peertube_prod
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints:
        - node.labels.peertube == 1

volumes:
  app_data:
  db_data:

networks:
  backend:
  traefik:
    external: true
