/* oxlint-disable @typescript-eslint/no-unused-expressions,@typescript-eslint/no-floating-promises */

import { HttpStatusCode } from '@peertube/peertube-models'
import { buildAbsoluteFixturePath } from '@peertube/peertube-node-utils'
import { makeGetRequest, makeRawRequest, PeerTubeServer } from '@peertube/peertube-server-commands'
import { expect } from 'chai'
import { pathExists } from 'fs-extra/esm'
import { readFile, writeFile } from 'fs/promises'
import { join, parse } from 'path'

// Default interval -> 5 minutes
export function dateIsValid (dateString: string | Date, interval = 300000) {
  const dateToCheck = new Date(dateString)
  const now = new Date()

  return Math.abs(now.getTime() - dateToCheck.getTime()) <= interval
}

export function expectStartWith (str: string, start: string) {
  expect(str.startsWith(start), `${str} does not start with ${start}`).to.be.true
}

export function expectNotStartWith (str: string, start: string) {
  expect(str.startsWith(start), `${str} does not start with ${start}`).to.be.false
}

export function expectEndWith (str: string, end: string) {
  expect(str.endsWith(end), `${str} does not end with ${end}`).to.be.true
}

// ---------------------------------------------------------------------------

export async function expectLogDoesNotContain (server: PeerTubeServer, str: string) {
  const content = await server.servers.getLogContent()

  expect(content.toString()).to.not.contain(str)
}

export async function expectLogContain (server: PeerTubeServer, str: string) {
  const content = await server.servers.getLogContent()

  expect(content.toString()).to.contain(str)
}

export async function testAvatarSize (options: {
  url: string
  imageName: string
  avatar: {
    width: number
    path: string
  }
}) {
  const { url, imageName, avatar } = options

  const { body } = await makeGetRequest({
    url,
    path: avatar.path,
    expectedStatus: HttpStatusCode.OK_200
  })

  const extension = parse(avatar.path).ext
  // We don't test big GIF avatars
  if (extension === '.gif' && avatar.width > 150) return

  const fixturePath = buildAbsoluteFixturePath(imageName + extension)
  const data = await readFile(fixturePath)
  const minLength = data.length - ((40 * data.length) / 100)
  const maxLength = data.length + ((40 * data.length) / 100)

  try {
    expect(body.length).to.be.above(minLength, `the generated image ${avatar.path} is way smaller than the recorded fixture ${fixturePath}`)
    expect(body.length).to.be.below(maxLength, `the generated image ${avatar.path} is way larger than the recorded fixture ${fixturePath}`)
  } catch (err) {
    if (process.env.AUTO_UPDATE_IMAGES === 'true') {
      await writeFile(fixturePath, body)
    }

    throw err
  }
}

export async function testImageGeneratedByFFmpeg (options: {
  url: string
  name: string
}) {
  if (process.env.ENABLE_FFMPEG_THUMBNAIL_PIXEL_COMPARISON_TESTS !== 'true') {
    console.log(
      'Pixel comparison of image generated by ffmpeg is disabled. ' +
        'You can enable it using `ENABLE_FFMPEG_THUMBNAIL_PIXEL_COMPARISON_TESTS=true env variable'
    )
    return
  }

  return testImage(options)
}

export async function testImage (options: {
  name: string
  url: string
}) {
  const { name, url } = options

  const { body } = await makeRawRequest({ url, expectedStatus: HttpStatusCode.OK_200 })
  const fixturePath = buildAbsoluteFixturePath(name)
  const data = await readFile(fixturePath)

  const sharp = (await import('sharp')).default
  const pixelmatch = (await import('pixelmatch')).default

  const img1 = sharp(body)
  const img1Metadata = await img1.metadata()

  const img2 = sharp(data)

  const errorMsg = `${url} image is not the same as ${name}`

  try {
    const result = pixelmatch(
      await img1.ensureAlpha().raw().toBuffer(),
      await img2.ensureAlpha().raw().toBuffer(),
      null,
      img1Metadata.width,
      img1Metadata.height,
      { threshold: 0.1 }
    )

    expect(result).to.be.below(100, errorMsg)
  } catch (err) {
    if (process.env.AUTO_UPDATE_IMAGES === 'true') {
      await writeFile(fixturePath, body)
    }

    // oxlint-disable-next-line preserve-caught-error
    throw new Error(`${errorMsg}: ${err.message}`)
  }
}

export async function downloadFile (url: string) {
  const { body } = await makeRawRequest({ url, responseType: 'arraybuffer', expectedStatus: HttpStatusCode.OK_200 })

  return Buffer.from(body)
}

export async function expectNotFound (urls: string[]) {
  for (const url of urls) {
    await makeRawRequest({ url, expectedStatus: HttpStatusCode.NOT_FOUND_404 })
  }
}

export function expectAllReplaced (previous: string[], current: string[]) {
  expect(previous).to.have.length.above(0)
  expect(current).to.have.length.above(0)

  for (const url of previous) {
    expect(current, url).to.not.include(url)
  }
}

// Unlike testImage(), compares two live URLs by pixel content instead of a URL against a fixture on disk
export async function expectSimilarImage (remoteUrl: string, originUrl: string) {
  const sharp = (await import('sharp')).default
  const pixelmatch = (await import('pixelmatch')).default

  const remoteImage = sharp(await downloadFile(remoteUrl))
  const originImage = sharp(await downloadFile(originUrl))

  const { width, height } = await remoteImage.metadata()
  const originMetadata = await originImage.metadata()
  expect({ width, height }, remoteUrl).to.deep.equal({ width: originMetadata.width, height: originMetadata.height })

  const differentPixels = pixelmatch(
    await remoteImage.ensureAlpha().raw().toBuffer(),
    await originImage.ensureAlpha().raw().toBuffer(),
    null,
    width,
    height,
    { threshold: 0.1 }
  )

  expect(differentPixels / (width * height), `${remoteUrl} is not the same image as ${originUrl}`).to.be.below(0.01)
}

// Matches remote/origin images by dimensions, then compares each matched pair with expectSimilarImage()
export async function expectSameImages (
  remoteImages: { fileUrl: string, width: number, height: number }[],
  originImages: { fileUrl: string, width: number, height: number }[]
) {
  let compared = 0

  for (const remoteImage of remoteImages) {
    const originImage = originImages.find(i => i.width === remoteImage.width && i.height === remoteImage.height)
    if (!originImage) continue

    await expectSimilarImage(remoteImage.fileUrl, originImage.fileUrl)
    compared++
  }

  expect(compared).to.be.above(0)
}

export async function testFileExistsOnFSOrNot (server: PeerTubeServer, directory: string, filePath: string, exist: boolean) {
  const base = server.servers.buildDirectory(directory)

  expect(await pathExists(join(base, filePath))).to.equal(exist)
}

export async function testImageSize (options: {
  buffer: Buffer
  width: number
  height: number
}) {
  const { buffer, width, height } = options

  const sharp = (await import('sharp')).default
  const img = sharp(buffer)
  const metadata = await img.metadata()

  expect(metadata.width).to.equal(width)
  expect(metadata.height).to.equal(height)
}

// ---------------------------------------------------------------------------

export async function checkBadStartPagination (url: string, path: string, token?: string, query = {}) {
  await makeGetRequest({
    url,
    path,
    token,
    query: { ...query, start: 'hello' },
    expectedStatus: HttpStatusCode.BAD_REQUEST_400
  })
}

export async function checkBadCountPagination (url: string, path: string, token?: string, query = {}) {
  await makeGetRequest({
    url,
    path,
    token,
    query: { ...query, count: 'hello' },
    expectedStatus: HttpStatusCode.BAD_REQUEST_400
  })

  await makeGetRequest({
    url,
    path,
    token,
    query: { ...query, count: 2000 },
    expectedStatus: HttpStatusCode.BAD_REQUEST_400
  })
}

export async function checkBadSort (url: string, path: string, token?: string, query = {}) {
  await makeGetRequest({
    url,
    path,
    token,
    query: { ...query, sort: 'hello' },
    expectedStatus: HttpStatusCode.BAD_REQUEST_400
  })
}

// ---------------------------------------------------------------------------

export async function checkVideoDuration (server: PeerTubeServer, videoUUID: string, duration: number) {
  const video = await server.videos.get({ id: videoUUID })

  expect(video.duration).to.be.approximately(duration, 1)

  for (const file of video.files) {
    const metadata = await server.videos.getFileMetadata({ url: file.metadataUrl })

    for (const stream of metadata.streams) {
      expect(Math.round(stream.duration)).to.be.approximately(duration, 1)
    }
  }
}
