import { VIDEO_FILE_TOKEN_LIFETIME } from '../../initializers/constants.js'
import { getValue, setValue } from './redis-client.js'

/**
 * Temporary tokens used as URL query parameters to access video static files.
 *
 * They live in Redis so a token generated by one process is accepted by every other one
 */

export type VideoTokenPayload = {
  videoUUID: string

  userId?: number

  // Timestamp in milliseconds, so a process can keep the resolved token in memory until it expires
  expires: number
}

export function setVideoToken (token: string, payload: VideoTokenPayload) {
  const ttl = getVideoTokenTTL(payload.expires)
  if (ttl <= 0) throw new Error('Cannot store an expired video token')

  return setValue(generateVideoTokenKey(token), JSON.stringify(payload), ttl)
}

export async function getVideoToken (token: string): Promise<VideoTokenPayload> {
  const value = await getValue(generateVideoTokenKey(token))
  if (!value) return undefined

  try {
    return JSON.parse(value)
  } catch {
    return undefined
  }
}

// Remaining lifetime of a token in milliseconds, never longer than the lifetime of a new token
export function getVideoTokenTTL (expires: number) {
  return Math.min(expires - Date.now(), VIDEO_FILE_TOKEN_LIFETIME)
}

// ---------------------------------------------------------------------------

function generateVideoTokenKey (token: string) {
  return 'video-token-' + token
}
