async function register ({ registerHook, peertubeHelpers }) {
  registerHook({
    target: 'filter:transcription.get-transcriber.result',

    handler: () => {
      return {
        name: 'test-plugin-transcriber',

        transcribe: async ({ language }) => {
          peertubeHelpers.logger.info('Generate subtitles with the test plugin transcriber, language: %s', language)

          return {
            language: language || 'en',

            content: 'WEBVTT\n\n00:00:00.000 --> 00:00:01.000\nGenerated by the test plugin transcriber\n'
          }
        }
      }
    }
  })
}

async function unregister () {
  return
}

module.exports = {
  register,
  unregister
}
