// Order of the tests we want to execute
import './server/stats'
import './check-params'
import './users/users'
import './videos/single-server'
import './videos/video-abuse'
import './videos/video-blacklist'
import './videos/video-blacklist-management'
import './videos/video-description'
import './videos/video-nsfw'
import './videos/video-privacy'
import './videos/services'
import './server/email'
import './server/config'
import './server/reverse-proxy'
