// Order of the tests we want to execute
import './videos/video-channels'
import './videos/video-transcoder'
import './videos/multiple-servers'
import './server/follows'
import './server/jobs'
import './videos/video-comments'
import './users/users-multiple-servers'
import './users/user-subscriptions'
import './server/handle-down'
import './videos/video-schedule-update'
import './videos/video-imports'
