// Order of the tests we want to execute
import './config'
import './check-params'
import './friends-basic'
import './users'
import './single-pod'
import './video-abuse'
import './video-blacklist'
import './video-blacklist-management'
import './video-description'
import './video-privacy'
import './services'
import './request-schedulers'
