// Order of the tests we want to execute
import './config'
import './check-params'
import './users'
import './single-server'
import './video-abuse'
import './video-blacklist'
import './video-blacklist-management'
import './video-description'
import './video-privacy'
import './services'
