// Order of the tests we want to execute
import './activitypub'
import './check-params'
import './moderation'
import './object-storage'
import './notifications'
import './redundancy'
import './search'
import './server'
import './transcoding'
import './users'
import './videos'
