// Order of the tests we want to execute
import './client'
import './misc-endpoints'
import './feeds/'
import './cli/'
import './api/'
import './peertube-runner/'
import './plugins/'
import './helpers/'
import './lib/'
