export type VideoSortField = 'name' | '-name'
                      | 'duration' | '-duration'
                      | 'createdAt' | '-createdAt'
                      | 'views' | '-views'
                      | 'likes' | '-likes'
