export type VideoSortField = 'name' | '-name'
                      | 'duration' | '-duration'
                      | 'publishedAt' | '-publishedAt'
                      | 'createdAt' | '-createdAt'
                      | 'views' | '-views'
                      | 'likes' | '-likes'
                      | 'trending' | '-trending'

export type CommentSortField = 'createdAt' | '-createdAt'
                          | 'totalReplies' | '-totalReplies'
